/**************************
 * MSP THROUGHPUT TEST CODE
 **************************/

#include <driverlib.h>
#include <ESP8266.h>
#include <UART_Driver.h>
#include "stdio.h"
#include "string.h"


void Initalise_Timer(void);
static int getTime(void);


int intTimes;
int timerValue;
#define TICKPERIOD      1000

static volatile int bufferSize = 2000;
char buffer[10000] = "BYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYTEBYT";


void Initialise_Timer(void)
{
    /* Timer_A UpMode Configuration Parameter */
    const Timer_A_UpModeConfig upConfig =
    {
            TIMER_A_CLOCKSOURCE_SMCLK,              // SMCLK Clock Source
            TIMER_A_CLOCKSOURCE_DIVIDER_12,          // SMCLK/12 = 1MHz
            TICKPERIOD,                             // 1000 tick period = 1 millisec per tick
            TIMER_A_TAIE_INTERRUPT_DISABLE,         // Disable Timer interrupt
            TIMER_A_CCIE_CCR0_INTERRUPT_ENABLE ,    // Enable CCR0 interrupt
            TIMER_A_DO_CLEAR                        // Clear value
    };

    int a = CS_getSMCLK();

    /* Configuring Timer_A0 for Up Mode */
    Timer_A_configureUpMode(TIMER_A0_BASE, &upConfig);

    /* Enabling interrupts */
    Interrupt_enableInterrupt(INT_TA0_0);
    Timer_A_clearTimer(TIMER_A0_BASE);
}

/* struct for MSP's serial */
eUSCI_UART_Config UART0Config =
{
     EUSCI_A_UART_CLOCKSOURCE_SMCLK,
     6,
     8,
     1,
     EUSCI_A_UART_NO_PARITY,
     EUSCI_A_UART_LSB_FIRST,
     EUSCI_A_UART_ONE_STOP_BIT,
     EUSCI_A_UART_MODE,
     EUSCI_A_UART_OVERSAMPLING_BAUDRATE_GENERATION
};

/* Struct for M5's serial */
eUSCI_UART_Config UART2Config =
{
     EUSCI_A_UART_CLOCKSOURCE_SMCLK,
     6,
     8,
     1,
     EUSCI_A_UART_NO_PARITY,
     EUSCI_A_UART_LSB_FIRST,
     EUSCI_A_UART_ONE_STOP_BIT,
     EUSCI_A_UART_MODE,
     EUSCI_A_UART_OVERSAMPLING_BAUDRATE_GENERATION
};

void main()
{
    MAP_WDT_A_holdTimer();
    Initialise_Timer();

    /*Ensure MSP432 is Running at 12 MHz*/
    FlashCtl_setWaitState(FLASH_BANK0, 2);
    FlashCtl_setWaitState(FLASH_BANK1, 2);
    PCM_setCoreVoltageLevel(PCM_VCORE1);
    CS_setDCOCenteredFrequency(CS_DCO_FREQUENCY_12);

    /*Initialize required hardware peripherals for the MSP's Serial Port*/
    MAP_GPIO_setAsPeripheralModuleFunctionInputPin(GPIO_PORT_P1, GPIO_PIN2 | GPIO_PIN3, GPIO_PRIMARY_MODULE_FUNCTION);
    MAP_UART_initModule(EUSCI_A0_BASE, &UART0Config);
    MAP_UART_enableModule(EUSCI_A0_BASE);
    MAP_UART_enableInterrupt(EUSCI_A0_BASE, EUSCI_A_UART_RECEIVE_INTERRUPT);
    MAP_Interrupt_enableInterrupt(INT_EUSCIA0);

    /*Initialize required hardware peripherals for the M5's Serial Port*/
    MAP_GPIO_setAsPeripheralModuleFunctionInputPin(GPIO_PORT_P3, GPIO_PIN2 | GPIO_PIN3, GPIO_PRIMARY_MODULE_FUNCTION);
    MAP_UART_initModule(EUSCI_A2_BASE, &UART2Config);
    MAP_UART_enableModule(EUSCI_A2_BASE);
    MAP_UART_enableInterrupt(EUSCI_A2_BASE, EUSCI_A_UART_RECEIVE_INTERRUPT);
    MAP_Interrupt_enableInterrupt(INT_EUSCIA2);

    MAP_Interrupt_enableMaster();

    /* Initiate first print on the Serial Terminal */
    UART_Printf(EUSCI_A0_BASE, "\n\n**********Communications Start***********\r\n");

    intTimes = 0;

      for (; bufferSize <= 10000; bufferSize += 2000)
      {


          char testBuffer[10000];
          strncpy(testBuffer, buffer, bufferSize);
          testBuffer[bufferSize] = '\0';
          UART_Printf(EUSCI_A0_BASE, "\r\n");

          int i = 1;
          for (; i < 6; i++)
          {
              char timeData[8]; //temp store for time in microseconds

              /* Start timer, send x bytes, stop timer */
              Timer_A_startCounter(TIMER_A0_BASE, TIMER_A_UP_MODE);
              UART_Printf(EUSCI_A2_BASE, testBuffer);
              Timer_A_stopTimer(TIMER_A0_BASE);
              sprintf(timeData, "%d", getTime());

              /* Print time taken to serial terminal*/
              UART_Printf(EUSCI_A0_BASE, "Attempt %i, %i bytes, time(ms): %i.", i, bufferSize, intTimes);
              UART_Printf(EUSCI_A0_BASE, timeData);
              UART_Printf(EUSCI_A0_BASE, "\r\n");

              intTimes = 0;
          }
      }
}

/* Returns time taken in microseconds */
static int getTime(void)
{
    int timetaken=0;
    timetaken = 0;

    /* Number of ticks (between 1 to 999) before the interrupt could occur */
    timetaken += Timer_A_getCounterValue(TIMER_A0_BASE);

    /* Clear Timer */
    Timer_A_clearTimer(TIMER_A0_BASE);

    return timetaken;
}

void TA0_0_IRQHandler(void)
{
    /* Increment global variable (count number of interrupts occurred, aka number of milliseconds) */
    intTimes++;

    /* Clear interrupt flag */
    Timer_A_clearCaptureCompareInterrupt(TIMER_A0_BASE, TIMER_A_CAPTURECOMPARE_REGISTER_0);
}

